import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>ezzy commerce</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1 className='font-bold text-4xl'>Next JS ecommerce store</h1>
    </div>
  );
}
